import click
import os
import json
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn

# naya
from paper2torch.parser import extract_text_from_pdf, extract_relevant_sections
from paper2torch.extractor import extract_sections, get_core_content
from paper2torch.generator import generate_pytorch_code
from paper2torch.validator import validate_code

console = Console()


@click.command()
@click.argument('pdf_path')
@click.option('--output', '-o', default='./output', help='Output folder path')
@click.option('--title', '-t', default='Unknown Paper', help='Paper title')
def main(pdf_path, output, title):
    """
    paper2torch — Convert research papers to PyTorch code.
    
    Usage: python cli.py paper.pdf --output ./generated
    """
    
    console.print(Panel.fit(
        "[bold red]paper2torch[/bold red] — Research Paper to PyTorch",
        border_style="red"
    ))
    
    # Step 1: PDF parse karo
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        transient=True
    ) as progress:
        
        task = progress.add_task("Parsing PDF...", total=None)
        
        try:
            pdf_data = extract_text_from_pdf(pdf_path)
            console.print(f"[green]✓[/green] PDF parsed — {pdf_data['total_pages']} pages found")
        except FileNotFoundError:
            console.print(f"[red]✗ PDF not found: {pdf_path}[/red]")
            return
        
        # Step 2: Sections extract karo
        progress.update(task, description="Extracting sections...")
        sections = extract_sections(pdf_data['full_text'])
        core_content = get_core_content(sections)
        console.print(f"[green]✓[/green] Sections extracted — {len(core_content)} chars")
        
        # Step 3: PyTorch code generate karo
        progress.update(task, description="Generating PyTorch code with Gemini...")
        result = generate_pytorch_code(core_content, title)
        console.print(f"[green]✓[/green] PyTorch code generated")
        
        # Step 4: Validate karo
        progress.update(task, description="Validating code...")
        validation = validate_code(result['model_code'])
        
        if validation['passed']:
            console.print(f"[green]✓[/green] Validation passed")
        else:
            console.print(f"[yellow]⚠[/yellow] Validation: {validation['summary']}")
    
    # Step 5: Output save karo
    os.makedirs(output, exist_ok=True)
    
    # model.py save karo
    model_path = os.path.join(output, 'model.py')
    with open(model_path, 'w', encoding='utf-8') as f:
        f.write(result['model_code'])
    
    # config.py save karo
    config_path = os.path.join(output, 'config.py')
    with open(config_path, 'w', encoding='utf-8') as f:
        f.write(result['config_code'])
    
    # README save karo
    readme_path = os.path.join(output, 'README_generated.md')
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(f"# {title}\n\n")
        f.write("## Generated by paper2torch\n\n")
        f.write("### Architecture Info\n\n")
        f.write(f"```json\n{result['architecture_info']}\n```\n\n")
        f.write("### Validation\n\n")
        f.write(f"- Status: {'✓ Passed' if validation['passed'] else '⚠ Issues found'}\n")
        f.write(f"- Summary: {validation['summary']}\n")
    
    console.print(Panel.fit(
        f"[bold green]Done![/bold green]\n\n"
        f"Files saved to [cyan]{output}[/cyan]\n"
        f"  • model.py\n"
        f"  • config.py\n"
        f"  • README_generated.md",
        border_style="green"
    ))


if __name__ == "__main__":
    main()